# Generated by Django 4.1.1 on 2022-09-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numberInvoice', models.IntegerField(max_length=100)),
                ('dateInvoice', models.DateField()),
                ('documentNumber', models.IntegerField()),
                ('amount', models.IntegerField(max_length=256)),
                ('unitValue', models.IntegerField()),
                ('discount', models.FloatField(max_length=100)),
                ('total', models.FloatField(max_length=100)),
                ('paidOut', models.FloatField(max_length=100)),
            ],
        ),
    ]
