# Generated by Django 4.1.1 on 2022-09-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='numberInvoice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paidOut',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(),
        ),
    ]
