# Generated by Django 4.1.1 on 2022-09-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_invoice_amount_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('documentType', models.CharField(max_length=100)),
                ('documentNumber', models.IntegerField()),
                ('mailAddress', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('nickName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
