# Generated by Django 4.1.1 on 2022-09-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('sellerCode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('documentType', models.CharField(max_length=100)),
                ('documentNumber', models.IntegerField()),
                ('mailAddress', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('nickName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
