# Generated by Django 4.1.1 on 2022-09-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_product'),
        ('authApp', '0005_seller'),
    ]

    operations = [
    ]
