from .clienteSerializer import CustomerSerializer
from .proveedorSerializer import ProveedorSerializer
from .logisticaSerializer import LogisticSerializer
from .vendedorSerializer import SellerSerializer
from .productoSerializer import ProductSerializer
from .administradorSerializer import AdministratorSerializer
